# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONUNBUFFERED True
ENV APP_HOME /app
WORKDIR $APP_HOME

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY . .

# Set the command to run the application using gunicorn
# Cloud Run sets the PORT environment variable automatically
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app